openapi: 3.1.0
info:
  title: My API
  version: 'v1'
paths:
  /v1/todos:
    get:
      summary: Get all todos
      operationId: getTodos
      tags:
        - Todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      operationId: createTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '200':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /v1/todos/{id}:
    delete:
      summary: Delete a todo by ID
      operationId: deleteTodo
      tags:
        - Todos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
  /v1/users:
    get:
      summary: Get all users or a user by UID
      operationId: getUsers
      tags:
        - Users
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            type: string
          description: UID of the user to retrieve
      responses:
        '200':
          description: A list of users or a specific user
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/User'
                  - $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        user_id:
          type: integer
    NewTodo:
      type: object
      properties:
        title:
          type: string
          example: "Sample Todo"
        user_id:
          type: integer
          example: 1
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        todos:
          type: array
          items:
            $ref: '#/components/schemas/Todo'
    NewUser:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john.doe@example.com"
        uid:
          type: string
          example: "unique_user_id"
